sudo: required
services: docker
jdk: oraclejdk8
language: groovy

before_install:
  - openssl aes-256-cbc -K $encrypted_089afaf79c27_key -iv $encrypted_089afaf79c27_iv -in variables.sh.enc -out variables.sh -d
  - curl -L https://github.com/docker/compose/releases/download/1.4.1/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
  - docker -v
  - sudo iptables -n --list "DOCKER" >/dev/null 2>&1 || sudo iptables -N DOCKER

install: ./installViaTravis.sh
script: ./buildViaTravis.sh

before_script:
  - . variables.sh
  - docker login -u ${DOCKER_HUB_USER} -p ${DOCKER_HUB_KEY} -e ${DOCKER_HUB_EMAIL}
after_script: docker logout
